[
  # Logger Macro Issues (False Positives)
  # These are from Dialyzer not understanding Logger macro expansions
  # The functions exist but are generated by macros at compile time
  ~r/Function Logger\.__do_log__\/4 does not exist/,
  ~r/Function Logger\.__should_log__\/2 does not exist/,
  
  # Optional Dependencies
  # Jason is optional but used in some modules
  ~r/Function Jason\.encode!?\/[12] does not exist/,
  ~r/Function Jason\.decode!?\/[12] does not exist/,
  
  # Mix Task Behavior
  # Mix.Task behavior callbacks not found in PLT
  {"lib/mix/tasks/ex_llm.cache.ex", :callback_info_missing},
  {"lib/mix/tasks/ex_llm.config.ex", :callback_info_missing},
  
  # Mix.shell is dynamically resolved at runtime
  ~r/Function Mix\.shell\/0 does not exist/
]